version: '2.1'

services:
  homeassistant:
    image: homeassistant/home-assistant
    container_name: homeassistant
    restart: always
    depends_on:
      deconz:
        condition: service_healthy
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/david/home-automation-configuration/homeassistant:/config
    healthcheck:
      test: 'curl -Lf http://localhost:8123'

  deconz:
    image: joch/deconz
    container_name: deconz
    restart: always
    network_mode: host
    volumes:
       - /home/david/home-automation-configuration/deconz:/root/.local/share/dresden-elektronik/deCONZ:rw
    devices:
      - /etc/localtime:/etc/localtime:ro
      - /dev/ttyUSB0:/dev/ttyUSB0
    healthcheck:
      test: 'curl -Lf http://localhost:8080 && sleep 20'

  appdaemon:
    image: johanssondavid/appdaemon2
    container_name: appdaemon
    restart: always
    depends_on:
      - homeassistant
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/david/home-automation-configuration/appdaemon/:/conf
