version: '2.1'

services:
  homeassistant:
    image: homeassistant/home-assistant:0.97.2
    container_name: homeassistant
    restart: always
    depends_on:
      deconz:
        condition: service_healthy
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/david/home-automation-configuration/homeassistant:/config
      - /home/david/.ssh:/root/.ssh
    healthcheck:
      test: 'exit 0'

  deconz:
    image: joch/deconz:2.05.32
    container_name: deconz
    restart: always
    network_mode: host
    volumes:
      - /home/david/home-automation-configuration/deconz:/root/.local/share/dresden-elektronik/deCONZ:rw
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    healthcheck:
      test: 'exit 0'

  appdaemon:
    image: acockburn/appdaemon:3.0.1
    container_name: appdaemon
    restart: always
    depends_on:
      homeassistant:
        condition: service_healthy
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/david/home-automation-configuration/appdaemon/:/conf

  influxdb:
    image: influxdb:1.7.0
    container_name: influxdb2
    restart: always
    network_mode: host
    volumes:
      # Data persistency
      - /home/david/data/influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:6.0.2
    user: "0"
    container_name: grafana4
    restart: always
    network_mode: host
    volumes:
      - /home/david/data/grafana:/var/lib/grafana
