version: '2.1'

services:
  homeassistant:
    image: homeassistant/home-assistant:0.70.0
    container_name: homeassistant
    restart: always
    depends_on:
      deconz:
        condition: service_healthy
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/david/home-automation-configuration/homeassistant:/config
      - /home/david/.ssh:/root/.ssh
    healthcheck:
      test: 'curl -Lf http://localhost:8123'

  deconz:
    image: joch/deconz:2.05.07
    container_name: deconz
    restart: always
    network_mode: host
    volumes:
      - /home/david/home-automation-configuration/deconz:/root/.local/share/dresden-elektronik/deCONZ:rw
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    healthcheck:
      test: 'curl -Lf http://localhost:8080 && sleep 20'

  appdaemon:
    image: acockburn/appdaemon:2.1.12
    container_name: appdaemon
    restart: always
    depends_on:
      - homeassistant
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/david/home-automation-configuration/appdaemon/:/conf
