homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 2
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
   api_password: !secret http
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
    monitored_conditions:
      - temperature
  - platform: command_line
    command: !secret ssh
    name: linnebo_temp
    unit_of_measurement: "°C"
    scan_interval: 600

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

switch:
  platform: command_line
  switches:
#    advent_kok:
#      command_on: curl -s http://192.168.0.15/b_on
#      command_off: curl -s http://192.168.0.15/b_off
#    advent_vardagsrum:
#      command_on: curl -s http://192.168.0.15/d_on
#      command_off: curl -s http://192.168.0.15/d_off
    livingroom_shelf:
      command_on: curl -s http://192.168.0.15/c_on
      command_off: curl -s http://192.168.0.15/c_off
#    receiver:
#      command_on: curl -s http://192.168.0.15/a_on
#      command_off: curl -s http://192.168.0.15/a_off

#volvooncall:
#    username: !secret volvo_on_call_user
#    password: !secret volvo_on_call_pw

device_tracker:
        #- platform: nmap_tracker
        #hosts: 192.168.0.1/24
        #consider_home: 900
        #track_new_devices: no
  - platform: bluetooth_tracker
    track_new_devices: False

input_select:
  house_mode:
    name: House Mode
    options:
    - Evening
    - Night
    - Day
    - Morning
    initial: Evening

    #apple_tv:
    #  - host: 192.168.0.14
    #    login_id: 00000000-3f5b-b3eb-3fa8-fb3ef8224211
    #    name: Apple TV

#influxdb:
#    host: 127.0.0.1
#    database: home_assistant
#    username: home-assistant
#    password: !secret http

input_boolean:
    lights_automation:
        name: Lights automation
        initial: on
    vacuum_automation:
        name: Vacuum automation
        initial: off
    wakeuplight_automation:
        name: Wake up light
        initial: off
    automations_off:
        name: All automations off
        initial: off

weblink:
    entities:
      - name: Deconz
        url: http://192.168.0.36:8080/
      - name: Portainer
        url: http://192.168.0.36:9000/

scene: !include_dir_list scenes

deconz:
    host: 127.0.0.1
    api_key: !secret deconz_key
    port: 8080

emulated_hue:
  off_maps_to_on_domains:
    - script
  expose_by_default: true
  exposed_domains:
    - script

input_datetime:
  wol:
    name: Wake Up Light
    has_date: false
    has_time: true
    initial: 05:15

homekit:

vacuum:
  - platform: xiaomi_miio
    host: 192.168.0.41
    token: !secret xiaomi
